### ISSUE TITLE
ios support v10.9.1

### ISSUE THREAD

**Issue by sarp86** [itheamc/mapbox_map_gl#11]
When will the new version 10.9.1 also be available for iOS? Any date for iOS support?

**Comment by itheamc** [comment]
IOS support may take some time due to the unavailability of MACOS device.

**Comment by sarp86** [comment]
How can we speed this up. Its important for our project :)

**Comment by itheamc** [comment]
> How can we speed this up. Its important for our project :)

To be very honest, I am not financially stable at this time to afford a MacBook to work on IOS side. But anyone having knowledge and understanding of Mapbox map and have a access of Macbook can contribute for IOS side implementation.

**Comment by srmncnk** [comment]
@itheamc Are you aware of the official wrapper around v10? https://pub.dev/packages/mapbox_maps_flutter

**Comment by itheamc** [comment]
> @itheamc Are you aware of the official wrapper around v10? https://pub.dev/packages/mapbox_maps_flutter

I was unaware of it and just came to know about it on Dec 18. I am happy with it that Mapbox team has officially developed plugin for flutter.
